name: Ansible CI

on:
  pull_request:
    branches: [ "main" ]
    paths: [ 'ansible/**','runme.sh','.github/workflows/ci-ansible.yml' ]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "VM_TOKEN=foo" > .env'
      - run: 'bash ./runme.sh'
      - uses: ansible-community/ansible-lint-action@v6
        with:
          args: "ansible"
